name: Setup ninja

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]
        version: [ '1.9.0', '1.10.2', '1.11.1', '1.12.1' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts

      - name: Set version
        uses: ./
        with:
          version: '${{ matrix.version }}'

      - name: Test ninja version
        shell: bash
        run: '[ "$(ninja --version)" == "${{ matrix.version }}" ]'
